export const GET_PRODUCTS_SUCCESS = "PRODUCTS/GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "PRODUCTS/GET_PRODUCTS_FAILURE";
export const GET_PRODUCTS_START = "PRODUCTS/GET_PRODUCTS_START";