export const TEAM_LIST_FETCH_SUCCESS = "TEAM/LIST_FETCH_SUCCESS";
export const TEAM_LIST_FETCH_START = "TEAM/LIST_FETCH_START";
export const TEAM_LIST_FETCH_ERROR = "TEAM/LIST_FETCH_ERROR";

export const TEAM_LIST_FETCH_INVALIDATE = "TEAM/LIST_FETCH_INVALIDATE";