export const MATCH_LIST_FETCH_SUCCESS = "MATCH/LIST_FETCH_SUCCESS";
export const MATCH_LIST_FETCH_START = "MATCH/LIST_FETCH_START";
export const MATCH_LIST_FETCH_ERROR = "MATCH/LIST_FETCH_ERROR";

export const MATCH_LIST_FETCH_INVALIDATE = "MATCH/LIST_FETCH_INVALIDATE";