// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190430140741_MatchPlayer-2")]
    partial class MatchPlayer2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataEntities.Entities.Match.MatchEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("IsStarted");

                    b.Property<string>("Location");

                    b.Property<int>("SecretaryId");

                    b.Property<DateTime>("StartsAt");

                    b.Property<int>("TeamAId");

                    b.Property<int>("TeamBId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("SecretaryId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("DataEntities.Entities.Match.MatchPlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("IsOnCourt");

                    b.Property<int?>("MatchEntityId");

                    b.Property<int>("MatchId");

                    b.Property<int?>("PlayerEntityId");

                    b.Property<int>("PlayerId");

                    b.Property<int?>("TeamEntityId");

                    b.Property<int>("TeamId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("MatchEntityId");

                    b.HasIndex("PlayerEntityId");

                    b.HasIndex("TeamEntityId");

                    b.ToTable("MatchPlayerEntity");
                });

            modelBuilder.Entity("DataEntities.Entities.Match.MatchPointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("IsMatchPoint");

                    b.Property<bool>("IsSetPoint");

                    b.Property<int?>("MatchEntityId");

                    b.Property<int>("MatchId");

                    b.Property<int>("PointNumber");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("MatchEntityId");

                    b.ToTable("MatchPoints");
                });

            modelBuilder.Entity("DataEntities.Entities.Match.PlayerPointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<int?>("MatchPointEntityId");

                    b.Property<int>("MatchPointId");

                    b.Property<int?>("PlayerEntityId");

                    b.Property<int>("PlayerId");

                    b.Property<int>("PointType");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("MatchPointEntityId");

                    b.HasIndex("PlayerEntityId");

                    b.ToTable("PlayerPoints");
                });

            modelBuilder.Entity("DataEntities.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<string>("Name");

                    b.Property<int>("Number");

                    b.Property<int>("TeamEntityId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("TeamEntityId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DataEntities.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<string>("Name");

                    b.Property<byte[]>("Photo");

                    b.Property<double>("Price");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DataEntities.Entities.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DataEntities.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("User");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataEntities.Entities.Match.MatchEntity", b =>
                {
                    b.HasOne("DataEntities.Entities.UserEntity", "SecretaryEntity")
                        .WithMany()
                        .HasForeignKey("SecretaryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataEntities.Entities.TeamEntity", "TeamAEntity")
                        .WithMany()
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataEntities.Entities.TeamEntity", "TeamBEntity")
                        .WithMany()
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataEntities.Entities.Match.MatchPlayerEntity", b =>
                {
                    b.HasOne("DataEntities.Entities.Match.MatchEntity", "MatchEntity")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchEntityId");

                    b.HasOne("DataEntities.Entities.PlayerEntity", "PlayerEntity")
                        .WithMany()
                        .HasForeignKey("PlayerEntityId");

                    b.HasOne("DataEntities.Entities.TeamEntity", "TeamEntity")
                        .WithMany()
                        .HasForeignKey("TeamEntityId");
                });

            modelBuilder.Entity("DataEntities.Entities.Match.MatchPointEntity", b =>
                {
                    b.HasOne("DataEntities.Entities.Match.MatchEntity", "MatchEntity")
                        .WithMany("Points")
                        .HasForeignKey("MatchEntityId");
                });

            modelBuilder.Entity("DataEntities.Entities.Match.PlayerPointEntity", b =>
                {
                    b.HasOne("DataEntities.Entities.Match.MatchPointEntity", "MatchPointEntity")
                        .WithMany("Players")
                        .HasForeignKey("MatchPointEntityId");

                    b.HasOne("DataEntities.Entities.PlayerEntity", "PlayerEntity")
                        .WithMany()
                        .HasForeignKey("PlayerEntityId");
                });

            modelBuilder.Entity("DataEntities.Entities.PlayerEntity", b =>
                {
                    b.HasOne("DataEntities.Entities.TeamEntity", "TeamEntity")
                        .WithMany("Players")
                        .HasForeignKey("TeamEntityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
