export const AUTH_LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const AUTH_LOGIN_START = "AUTH/LOGIN_START";
export const AUTH_lOGIN_ERROR = "AUTH/lOGIN_ERROR";

export const AUTH_REGISTER_START = "AUTH/AUTH_REGISTER_START";
export const AUTH_REGISTER_ERROR = "AUTH/AUTH_REGISTER_ERROR";
export const AUTH_REGISTER_SUCCESS = "AUTH/REGISTER_SUCCESS";

export const AUTH_LOGOUT_SUCCESS = "AUTH/LOGOUT_SUCCESS";

export const AUTH_INFO_SUCCESS = "AUTH/INFO_SUCCESS";
export const AUTH_INFO_START = "AUTH/INFO_START";
export const AUTH_INFO_ERROR = "AUTH/INFO_ERROR";